### ISSUE TITLE
Callback support?

### ISSUE THREAD

**Issue by vanrein** [pief/python-netsnmpagent#18]
Thank you for doing this work!  I experienced the same problem as you -- hardly any support for SNMP agents other than through C or Perl.
I think your model is nicer than the "push persist" mode of snmpd, but snmpd is still better suited for interactions with the environment -- local modifications over SNMP, and on-the-spot lookups in response to SNMP inquiries.
Have you considered permitting callback functions to make that sort of thing possible with your agent?  Matching against a beginning-of-OID as in snmpd should work nicely.  Such a construct could implement more dynamic getting, as wel as setting of values than now possible with python-netsnmpagent.

**Comment by pief** [comment]
Closing for now as no patch received. Feel free to reopen the topic with a PR if desired.
