### ISSUE TITLE
 python: undefined symbol: snmp_register_callback

### ISSUE THREAD

**Issue by robmool** [pief/python-netsnmpagent#26]
Hello,

I am trying to use the Python package netsnmpagent-0.5.3.tar.gz to setup a sub-agent. When I run the example "run_simple_agent.sh" I get the following error:

AttributeError: python: undefined symbol: snmp_register_callback

Script output:
* Preparing snmpd environment...
* Our snmpd instance is now listening on localhost, port 5555.
  From a second console, use the net-snmp command line utilities like this:

    cd /home/robm/snmp/src/python/netsnmpagent-0.5.3/examples
    snmpwalk -v 2c -c public -M+. localhost:5555 SIMPLE-MIB::simpleMIB
    snmptable -v 2c -c public -M+. -Ci localhost:5555 SIMPLE-MIB::firstTable
    snmpget -v 2c -c public -M+. localhost:5555 SIMPLE-MIB::simpleInteger.0
    snmpset -v 2c -c simple -M+. localhost:5555 SIMPLE-MIB::simpleInteger.0 i 123

* Starting the simple example agent...
Traceback (most recent call last):
  File "simple_agent.py", line 47, in <module>
    import netsnmpagent
  File "/home/robm/snmp/src/python/netsnmpagent-0.5.3/netsnmpagent.py", line 24, in <module>
    from netsnmpapi import *
  File "/home/robm/snmp/src/python/netsnmpagent-0.5.3/netsnmpapi.py", line 55, in <module>
    for f in [ libnsa.snmp_register_callback ]:
  File "/usr/lib/python2.7/ctypes/__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: python: undefined symbol: snmp_register_callback

I am using the net-snmp-5.7.3 package which I configured the following way:
configure --with-mib-modules=smux

Any help will be appreciated.

Kind regards,
Rob

**Comment by pief** [comment]
Try this in the Python interpreter interactively to mimic what the agent does:

```
>>> import ctypes, ctypes.util
>>> libnsa = ctypes.cdll.LoadLibrary(ctypes.util.find_library("netsnmpagent"))
>>> libnsa.snmp_register_callback
<_FuncPtr object at 0x7f1f8725a600>
```

This is what it _should_ look like, with a similar hex address of course. If it doesn't, you're building net-snmp wrong. Check if you need to include some `configure` switch to include callback support.

Also maybe worth to take a look at how your OS distribution builds net-snmp.

**Comment by robmool** [comment]
This is my output from the Python interpreter:

```
>>> import ctypes, ctypes.util
>>> libnsa = ctypes.cdll.LoadLibrary(ctypes.util.find_library("netsnmpagent"))
>>> libnsa.snmp_register_callback
<_FuncPtr object at 0x7f1f8725a600>
[debian8-32:robm]  python
Python 2.7.9 (default, Mar  1 2015, 18:22:53) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ctypes, ctypes.util
>>> libnsa = ctypes.cdll.LoadLibrary(ctypes.util.find_library("netsnmpagent"))
>>> libnsa.snmp_register_callback
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/ctypes/__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: python: undefined symbol: snmp_register_callback
```

**Comment by robmool** [comment]
Fixed the above problem by adding the net-snmp library directory in the file "/etc/ld.so.conf" and executing "ldconfig".

**Comment by robmool** [comment]
Now the example is working correctly.
Thank you for your help.

**Comment by chinmay0900** [comment]
Could you help me out with the steps you followed to solve this problem. I am facing the same issue and I am doing this on a system running buildroot.
