### ISSUE TITLE
Cannot update table entry

### ISSUE THREAD

**Issue by robmool** [pief/python-netsnmpagent#27]
Hi,

I'm trying to update a table entry with snmpset but I always get an error.

I used the MIB "SIMPLE-MIB.txt" and the python program "simple_agent.py" to play with. First I changed the lines "MAX-ACCESS" to  "read-write". Next I updated a simple object which worked fine and then I tried the update a table entry which failed.

Traces:
```
 $ snmpget -v 2c -c public -m$PWD/mibs/SIMPLE-MIB.txt localhost:5555 SIMPLE-MIB::simpleInteger.0
SIMPLE-MIB::simpleInteger.0 = INTEGER: 0
$ snmpset -v 2c -c private -m$PWD/mibs/SIMPLE-MIB.txt localhost:5555 SIMPLE-MIB::simpleInteger.0 i 123
SIMPLE-MIB::simpleInteger.0 = INTEGER: 123
$ snmpget -v 2c -c public -m$PWD/mibs/SIMPLE-MIB.txt localhost:5555 SIMPLE-MIB::simpleInteger.0       
SIMPLE-MIB::simpleInteger.0 = INTEGER: 123
$  snmpget -v 2c -c public -m$PWD/mibs/SIMPLE-MIB.txt localhost:5555 SIMPLE-MIB::secondTableEntryDesc.1
SIMPLE-MIB::secondTableEntryDesc.1 = STRING: foo0
$  snmpset -v 2c -c private -m$PWD/mibs/SIMPLE-MIB.txt localhost:5555 SIMPLE-MIB::secondTableEntryDesc.1 s hello
Error in packet.
Reason: notWritable (That object does not support modification)
Failed object: SIMPLE-MIB::secondTableEntryDesc.1
```

Any ideas?

Kind regards,
Rob

**Comment by pief** [comment]
Not sure this is a code issue really, it could also be a limitation of the SIMPLE-MIB.

If you can come up with a MIB shipped with net-snmp where setting a table value works, we could compare the way it's written (eg. which elements have which MAX-ACCESS) to SIMPLE-MIB to rule this possibility out.

**Comment by robmool** [comment]
This is what I used, see attachment.
[example.zip](https://github.com/pief/python-netsnmpagent/files/744279/example.zip)

**Comment by pief** [comment]
As I said, find a MIB shipped with net-snmp where setting a table value works and compare that MIB to SIMPLE-MIB, then you might find something.

**Comment by robmool** [comment]
I used the NET-SNMP-EXAMPLES-MIB.txt MIB file shipped with the net-snmp package. Did some tests on a table and works fine.

Output:
```
$ snmpwalk  -v 2c -c public -m$PWD/mibs/NET-SNMP-EXAMPLES-MIB.txt localhost:5555 netSnmpIETFWGTable
NET-SNMP-EXAMPLES-MIB::nsIETFWGChair1."snmpv3" = STRING: "Russ Mundy"
NET-SNMP-EXAMPLES-MIB::nsIETFWGChair2."snmpv3" = STRING: "David Harrington"

$ snmpget -v 2c -c public -m$PWD/mibs/NET-SNMP-EXAMPLES-MIB.txt localhost:5555 NET-SNMP-EXAMPLES-MIB::nsIETFWGChair1.\"snmpv3\"
NET-SNMP-EXAMPLES-MIB::nsIETFWGChair1."snmpv3" = STRING: "Russ Mundy"

$ snmpset -v 2c -c private -m$PWD/mibs/NET-SNMP-EXAMPLES-MIB.txt localhost:5555 NET-SNMP-EXAMPLES-MIB::nsIETFWGChair1.\"snmpv3\" s "Rob"
NET-SNMP-EXAMPLES-MIB::nsIETFWGChair1."snmpv3" = STRING: "Rob"

$ snmpget -v 2c -c public -m$PWD/mibs/NET-SNMP-EXAMPLES-MIB.txt localhost:5555 NET-SNMP-EXAMPLES-MIB::nsIETFWGChair1.\"snmpv3\"
NET-SNMP-EXAMPLES-MIB::nsIETFWGChair1."snmpv3" = STRING: "Rob"
```

Now, used the same MIB with your python example and the snmpset still fails on a table entry.
Output:
```
$ snmpget -v 2c -c public -m$PWD/mibs/MY-NET-SNMP-EXAMPLES-MIB.txt localhost:5555 MY-NET-SNMP-EXAMPLES-MIB::nsIETFWGChair1.\"snmpv3\"
 MY-NET-SNMP-EXAMPLES-MIB::nsIETFWGChair1."snmpv3" = STRING: "Russ Mundy"
$ snmpset -v 2c -c private -m$PWD/mibs/MY-NET-SNMP-EXAMPLES-MIB.txt localhost:5555 MY-NET-SNMP-EXAMPLES-MIB::nsIETFWGChair1.\"snmpv3\" s "Rob"
 Error in packet.
 Reason: notWritable (That object does not support modification)
 Failed object: MY-NET-SNMP-EXAMPLES-MIB::nsIETFWGChair1."snmpv3"

```
Have you succeeded to update a table entry with snmpset using a python subagent?

**Comment by sakulh** [comment]
I have same problem. Any change or solution? Thank you.

**Comment by robmool** [comment]
So far I haven't received any updates after my last respond.

**Comment by pief** [comment]
If I had the time myself and was facing the issue I would probably be looking at it. Seeing that I don't and need to make a living somehow like everybody else, feel free to investigate the issue yourself (that's why it's Open Source) and send me a pull request suitable for merging.
