### ISSUE TITLE
No support for OctetStrings with zeros.

### ISSUE THREAD

**Issue by kfir-drivenets** [pief/python-netsnmpagent#28]
The library uses `ctypes.create_string_buffer` and `ctypes.string_at` etc.
This causes an issue when trying to work with buffers that should be returned as hexadecimal.
For example if I want to return IPv6 address of MAC as an octet string and one of the bytes is zero I will get a partial result (the prefix of the buffer until we hit the zero byte).

This can most likely be fixed by using `ctypes.c_ubyte * N` to create the buffers instead `ctype.create_string_buffer`

**Comment by pief** [comment]
Can you prepare a pull request for this issue? It should pass the few tests that are there of course :)
