### ISSUE TITLE
Couldn't install from github

### ISSUE THREAD

**Issue by thekvs** [pief/python-netsnmpagent#30]
We need the latest version of netsnmpagent package with proper python3 support, but unfortunately couldn't install it directly from github since there is no setup.py and version in pypi archive doesn't work with python3.4.

Please make project installable directly from github or publish new fresh release on pypi.

**Comment by thekvs** [comment]
A bit of clarification: we use dh-virtualenv to automatically create and package python virtualenvs in deb format, so we need to install packages automatically from requirements.txt file using only pip utility, i.e. without running make etc.

**Comment by pief** [comment]
I'd have to come up with a replacement for setup.py.in first. In the mean time, would it help you if I make a new release from master and put that on PyPi?

**Comment by thekvs** [comment]
Yes, new release will help.

**Comment by pief** [comment]
Fixed by releasing 0.6.0 with Python 3 support just now.
