### ISSUE TITLE
No Gauge32 available

### ISSUE THREAD

**Issue by pre101** [pief/python-netsnmpagent#31]
Hi, 

I want to implement a gauge, but netsnmpAgent has no Gauge32.
e.g.
```python
activeSessionAvg = agent.Gauge32(
    oidstr   = ....,
    initval  = 0,
    writable = False
)
```
Error message is:
```
AttributeError: 'netsnmpAgent' object has no attribute 'Gauge32'
```

**Comment by pief** [comment]
https://github.com/pief/python-netsnmpagent/blob/master/tests/test_03_netsnmpagent_snmpobjs.py#L431

**Comment by pief** [comment]
Did you see that Unsigned32 results in a Gauge32 object? Can this issue be closed?

**Comment by pre101** [comment]
Unfortunately I'm not be able to run my script within netsnmpagent. snmpd report only "No OID" or Timeout. As time is running out I have to use snmp pass scripts which works. May be I found time to get the error later on. So closed this issue here.
