### ISSUE TITLE
I can't update row Counter64

### ISSUE THREAD

**Issue by jzegarrav** [pief/python-netsnmpagent#37]
Hi,

I ran the simple agent to read linux network interfaces eth0, eth1 and eth2:

{'NETWORKZ-MIB::firstTable': {'type': 'Table',
                              'value': {0: {2: {'type': 'OctetString', 'value': 'Unknown place'},
                                            3: {'type': 'Counter64', 'value': 0}},
                                        '1': {2: 'eth0', 3: 204064872L},
                                        '2': {2: 'eth1', 3: 134064843},
                                        '3': {2: 'eth2', 3: 988190442}}},

When I execute:

 snmpwalk -v 2c -c public -M+. localhost:5555 NETWORKZ-MIB::simpleMIB
 shows me:
NETWORKZ-MIB::ifDescr."1" = STRING: eth0
NETWORKZ-MIB::ifDescr."2" = STRING: eth1
NETWORKZ-MIB::ifDescr."3" = STRING: eth2
NETWORKZ-MIB::ifInBytes."1" = Counter64: 204064872
NETWORKZ-MIB::ifInBytes."2" = Counter64: 134064843
NETWORKZ-MIB::ifInBytes."3" = Counter64: 988190442

When I execute again the snmpwalk, the result is the same. I can't update Counter64 values

The code is:

# Add the first table row
firstTableRow1 = firstTable.addRow([agent.DisplayString("1")])
firstTableRow1.setRowCell(2, agent.DisplayString("eth0"))
firstTableRow1.setRowCell(3, agent.Counter64(get_in_bytes("eth0")))

# Add the second table row
firstTableRow2 = firstTable.addRow([agent.DisplayString("2")])
firstTableRow2.setRowCell(2, agent.DisplayString("eth1"))
#firstTableRow2.setRowCell(3, agent.Integer32(28))
firstTableRow2.setRowCell(3, agent.Counter64(get_in_bytes("eth1")))

# Add the third table row
firstTableRow3 = firstTable.addRow([agent.DisplayString("3")])
firstTableRow3.setRowCell(2, agent.DisplayString("eth2"))
#firstTableRow3.setRowCell(3, agent.Integer32(18))
firstTableRow3.setRowCell(3, agent.Counter64(get_in_bytes("eth2")))

The function get_in_bytes() allow me to get the input bytes on the interface

Juan Carlos

**Comment by pief** [comment]
The tables keep reporting the same values because the simple agent does not update the table. You would have to modify the code inside ``while (loop)`` to periodically refresh the table. However you would then notice that the code does either AgentX packet processing _or_ updating but not both at the same time. That's what you need threading for. Have a look at the threading agent and use it as a starting base for your own agent but implemented with tables.
